### ISSUE TITLE
UnknownObjectException

### ISSUE THREAD

**Issue by JulienPalard** [AFPy/PyDocTeur#21]
```
INFO:root:Trying to find PR number from payload
ERROR:pydocteur:Exception on / [POST]
Traceback (most recent call last):
  File "/srv/data/web/vhosts/default/local/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/srv/data/web/vhosts/default/local/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/srv/data/web/vhosts/default/local/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/srv/data/web/vhosts/default/local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/srv/data/web/vhosts/default/local/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/srv/data/web/vhosts/default/local/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "./pydocteur/__init__.py", line 63, in process_incoming_payload
    pr = get_pull_request(gh, payload)
  File "./pydocteur/utils/get_pr.py", line 34, in get_pull_request
    return gh_repo.get_pull(pr_number)
  File "/srv/data/web/vhosts/default/local/lib/python3.8/site-packages/github/Repository.py", line 2671, in get_pull
    headers, data = self._requester.requestJsonAndCheck(
  File "/srv/data/web/vhosts/default/local/lib/python3.8/site-packages/github/Requester.py", line 317, in requestJsonAndCheck
    return self.__check(
  File "/srv/data/web/vhosts/default/local/lib/python3.8/site-packages/github/Requester.py", line 342, in __check
    raise self.__createException(status, responseHeaders, output)
github.GithubException.UnknownObjectException: 404 {"message": "Not Found", "documentation_url": "https://docs.github.com/rest/reference/pulls#get-a-pull-request"}
INFO:root:Trying to find PR number from payload
WARNING:root:Unknown payload, returning None
INFO:root:Payload received corresponds to issue, PR not found or PR already merged or closed, ignoring.
```

**Comment by Seluj78** [comment]
Closing for now as it seems good ?
