### ISSUE TITLE
Exception during merge

### ISSUE THREAD

**Issue by JulienPalard** [AFPy/PyDocTeur#41]
```
Dec  2 00:16:29 sd-160097 gunicorn[5172]: Exception on / [POST]
Dec  2 00:16:29 sd-160097 gunicorn[5172]: Traceback (most recent call last):
Dec  2 00:16:29 sd-160097 gunicorn[5172]:   File "/home/pydocteur-afpy-org/venv/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
Dec  2 00:16:29 sd-160097 gunicorn[5172]:     response = self.full_dispatch_request()
Dec  2 00:16:29 sd-160097 gunicorn[5172]:   File "/home/pydocteur-afpy-org/venv/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
Dec  2 00:16:29 sd-160097 gunicorn[5172]:     rv = self.handle_user_exception(e)
Dec  2 00:16:29 sd-160097 gunicorn[5172]:   File "/home/pydocteur-afpy-org/venv/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
Dec  2 00:16:29 sd-160097 gunicorn[5172]:     reraise(exc_type, exc_value, tb)
Dec  2 00:16:29 sd-160097 gunicorn[5172]:   File "/home/pydocteur-afpy-org/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
Dec  2 00:16:29 sd-160097 gunicorn[5172]:     raise value
Dec  2 00:16:29 sd-160097 gunicorn[5172]:   File "/home/pydocteur-afpy-org/venv/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
Dec  2 00:16:29 sd-160097 gunicorn[5172]:     rv = self.dispatch_request()
Dec  2 00:16:29 sd-160097 gunicorn[5172]:   File "/home/pydocteur-afpy-org/venv/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
Dec  2 00:16:29 sd-160097 gunicorn[5172]:     return self.view_functions[rule.endpoint](**req.view_args)
Dec  2 00:16:29 sd-160097 gunicorn[5172]:   File "/home/pydocteur-afpy-org/src/pydocteur/app.py", line 65, in process_incoming_payload
Dec  2 00:16:29 sd-160097 gunicorn[5172]:     state_dict.get(state, comment_pr)(state=state, pr=pr)
Dec  2 00:16:29 sd-160097 gunicorn[5172]:   File "/home/pydocteur-afpy-org/src/pydocteur/actions.py", line 86, in merge_and_thank_contributors
Dec  2 00:16:29 sd-160097 gunicorn[5172]:     pr.merge(merge_method="squash", commit_message="")
Dec  2 00:16:29 sd-160097 gunicorn[5172]:   File "/home/pydocteur-afpy-org/venv/lib/python3.7/site-packages/github/PullRequest.py", line 866, in merge
Dec  2 00:16:29 sd-160097 gunicorn[5172]:     "PUT", self.url + "/merge", input=post_parameters
Dec  2 00:16:29 sd-160097 gunicorn[5172]:   File "/home/pydocteur-afpy-org/venv/lib/python3.7/site-packages/github/Requester.py", line 319, in requestJsonAndCheck
Dec  2 00:16:29 sd-160097 gunicorn[5172]:     verb, url, parameters, headers, input, self.__customConnection(url)
Dec  2 00:16:29 sd-160097 gunicorn[5172]:   File "/home/pydocteur-afpy-org/venv/lib/python3.7/site-packages/github/Requester.py", line 342, in __check
Dec  2 00:16:29 sd-160097 gunicorn[5172]:     raise self.__createException(status, responseHeaders, output)
Dec  2 00:16:29 sd-160097 gunicorn[5172]: github.GithubException.GithubException: 405 {"message": "Required status check \"check-title\" is queued. 1 review requesting changes by reviewers with write access.", "documentation_url": "https://docs.github.com/articles/about-protected-branches"}
```

**Comment by JulienPalard** [comment]
Ça arrive parce que check-title est ignorée, donc le bot essaye de merger avant que check-title ne soit passée.

Il ne faut probablement pas l'ignorer, tout en s'évitant d'une autre manière de flapper entre "les tests passent" et "les tests passent pas" dès que ce test se fait.

**Comment by Seluj78** [comment]
Peut etre un flag `is_merged` dans `get_pr_runs` qui ignore ou non ce test la ?

**Comment by JulienPalard** [comment]
Closed by https://github.com/AFPy/PyDocTeur/pull/43
