### ISSUE TITLE
Exception in production

### ISSUE THREAD

**Issue by JulienPalard** [AFPy/PyDocTeur#55]
```
Dec 15 09:57:20 sd-160097 gunicorn[4737]: Traceback (most recent call last):
Dec 15 09:57:20 sd-160097 gunicorn[4737]:   File "/home/pydocteur-afpy-org/venv/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
Dec 15 09:57:20 sd-160097 gunicorn[4737]:     response = self.full_dispatch_request()
Dec 15 09:57:20 sd-160097 gunicorn[4737]:   File "/home/pydocteur-afpy-org/venv/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
Dec 15 09:57:20 sd-160097 gunicorn[4737]:     rv = self.handle_user_exception(e)
Dec 15 09:57:20 sd-160097 gunicorn[4737]:   File "/home/pydocteur-afpy-org/venv/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
Dec 15 09:57:20 sd-160097 gunicorn[4737]:     reraise(exc_type, exc_value, tb)
Dec 15 09:57:20 sd-160097 gunicorn[4737]:   File "/home/pydocteur-afpy-org/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
Dec 15 09:57:20 sd-160097 gunicorn[4737]:     raise value
Dec 15 09:57:20 sd-160097 gunicorn[4737]:   File "/home/pydocteur-afpy-org/venv/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
Dec 15 09:57:20 sd-160097 gunicorn[4737]:     rv = self.dispatch_request()
Dec 15 09:57:20 sd-160097 gunicorn[4737]:   File "/home/pydocteur-afpy-org/venv/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
Dec 15 09:57:20 sd-160097 gunicorn[4737]:     return self.view_functions[rule.endpoint](**req.view_args)
Dec 15 09:57:20 sd-160097 gunicorn[4737]:   File "/home/pydocteur-afpy-org/src/pydocteur/app.py", line 69, in process_incoming_payload
Dec 15 09:57:20 sd-160097 gunicorn[4737]:     state_dict.get(state, comment_pr)(state=state, pr=pr)
Dec 15 09:57:20 sd-160097 gunicorn[4737]:   File "/home/pydocteur-afpy-org/src/pydocteur/actions.py", line 84, in merge_and_thank_contributors
Dec 15 09:57:20 sd-160097 gunicorn[4737]:     pr.create_issue_comment(warning_body + END_OF_BODY.format(state=state, version=VERSION))
Dec 15 09:57:20 sd-160097 gunicorn[4737]:   File "/home/pydocteur-afpy-org/venv/lib/python3.7/site-packages/github/PullRequest.py", line 459, in create_issue_c
omment
Dec 15 09:57:20 sd-160097 gunicorn[4737]:     "POST", self.issue_url + "/comments", input=post_parameters
Dec 15 09:57:20 sd-160097 gunicorn[4737]:   File "/home/pydocteur-afpy-org/venv/lib/python3.7/site-packages/github/Requester.py", line 319, in requestJsonAndCh
eck
Dec 15 09:57:20 sd-160097 gunicorn[4737]:     verb, url, parameters, headers, input, self.__customConnection(url)
Dec 15 09:57:20 sd-160097 gunicorn[4737]:   File "/home/pydocteur-afpy-org/venv/lib/python3.7/site-packages/github/Requester.py", line 342, in __check
Dec 15 09:57:20 sd-160097 gunicorn[4737]:     raise self.__createException(status, responseHeaders, output)
Dec 15 09:57:20 sd-160097 gunicorn[4737]: github.GithubException.GithubException: 403 {"message": "At least one email address must be verified to do that.", "d
ocumentation_url": "https://docs.github.com/articles/adding-an-email-address-to-your-github-account"}
```

**Comment by JulienPalard** [comment]
@Seluj78 Have you seen this issue?

**Comment by Seluj78** [comment]
Nope, let me check the settings of the pydocteur user

**Comment by Seluj78** [comment]
Welll the bot's email was verified. I did it again jsut in case

**Comment by Seluj78** [comment]
Closing as it shouldn't happen again
